### ISSUE TITLE
Please update npm package with your new 'dist' 

### ISSUE THREAD

**Issue by victorvhpg** [pankod/react-native-store-rating#20]
I wanna use '.onSendReview', but your npm package has a old 'dist' that hasn't  '.onSendReview'

**Comment by Cthalin** [comment]
You can delete the 'dist' folder and recompile it by yourself just by running 'tsc' in the module directory.

**Comment by chill-patel** [comment]
@Cthalin Thanks also created pull request for same

**Comment by flascaray** [comment]
+1

**Comment by omeraplak** [comment]
Hi,
We've released 1.0.2. Thank you for your patience
