### ISSUE TITLE
Request for buttons style props

### ISSUE THREAD

**Issue by takumade** [pankod/react-native-store-rating#31]
**Feature Request**

Hello how are you? I am requesting for **button style props** functionality. Please

**Comment by nabruzzi** [comment]
Hello! 
Make this: 

` const rateModalStyles = StyleSheet.create({
    button: {
      backgroundColor: 'blue',
      marginHorizontal: 5,
    },
    buttonCancel: {
      backgroundColor: 'white',
    },
  });
  
  
  
        <RateModal
        //(...)
          styles={rateModalStyles}
          />


  `

**Comment by phoscoder** [comment]
Ok Thanks😁👍
